//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clinic.ApplicationData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class clinicEntities : DbContext
    {
        public clinicEntities()
            : base("name=clinicEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<diagnosis> diagnosis { get; set; }
        public DbSet<doctors> doctors { get; set; }
        public DbSet<patients> patients { get; set; }
        public DbSet<receptions> receptions { get; set; }
        public DbSet<roles> roles { get; set; }
        public DbSet<site> site { get; set; }
        public DbSet<specializations> specializations { get; set; }
        public DbSet<status> status { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
