//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clinic.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class receptions
    {
        public int id_reception { get; set; }
        public Nullable<int> id_patient { get; set; }
        public Nullable<int> id_doctor { get; set; }
        public Nullable<System.DateTime> date_reception { get; set; }
        public Nullable<System.TimeSpan> time_reception { get; set; }
        public Nullable<int> id_status { get; set; }
        public string symptoms { get; set; }
        public Nullable<int> id_diagnosis { get; set; }
        public string treatment { get; set; }
    
        public virtual diagnosis diagnosis { get; set; }
        public virtual doctors doctors { get; set; }
        public virtual patients patients { get; set; }
        public virtual status status { get; set; }
    }
}
