//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clinic.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class specializations
    {
        public specializations()
        {
            this.doctors = new HashSet<doctors>();
        }
    
        public int id_specialization { get; set; }
        public string specialization_name { get; set; }
    
        public virtual ICollection<doctors> doctors { get; set; }
    }
}
