//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clinic.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class status
    {
        public status()
        {
            this.receptions = new HashSet<receptions>();
        }
    
        public int id_status { get; set; }
        public string status_name { get; set; }
    
        public virtual ICollection<receptions> receptions { get; set; }
    }
}
